### ISSUE TITLE
BinomFluct normal approximation 

### ISSUE THREAD

**Issue by sophiaandaloro** [NESTCollaboration/nest#108]
The line here: 
https://github.com/NESTCollaboration/nest/blob/9363b9689d9fd7afaeef8cbf4178a0baeb2bcba9/src/NEST.cpp#L27
Determines when the normal approximation can be used.

Reference: https://en.wikipedia.org/wiki/Binomial_distribution#Normal_approximation 
"One rule is that for n > 5 the normal approximation is adequate if the absolute value of the skewness is strictly less than 1/3"

This is the least rigorous of the approximation conditions. Either we should up the conditions to higher statistics to play it safe, or go with a more stringent approximation condition. This causes a mismatch as-is between `BinomFluct` and other out-of-the-box Binomial sampling packages (in python). At the very least we need to change this to a `<=` condition in the line I link above.

**Comment by sophiaandaloro** [comment]
Also pretty sure the wiki is incorrect:
See this source: https://www.statisticshowto.com/probability-and-statistics/binomial-theorem/normal-approximation-to-the-binomial/

Other sources declare that it is not that N0>5, but _actually_ you need N0*p AND N0*(1-p) to be >5. So for an average g1~0.1, we are looking at a factor of 10 off for normal approximation!

**Comment by mszydagis** [comment]
I blame Jelle haha, I just followed what he told me a few months ago... I am tagging @grischbieter  for fixing this.

**Comment by sophiaandaloro** [comment]
From wiki:

This 3-standard-deviation rule is equivalent to the following conditions, which also imply the first rule above.
n > 9*(1-p)/p and n > 9*p/(1-p)

I think this is the safest case we can use while still resorting to normal approximations when n is large enough. (Just FYI Greg)

**Comment by grischbieter** [comment]
If I'm following all of this correctly, I interpret that we can replace the current if-statement with:
`if (N0 <= 9.*(1.-prob)/prob || N0 <= 9.*prob/(1.-prob)){
          //use binomial distribution;
 } else{
         //use normal approximation;
 ;`
Based on what the wikipedia page says, this takes into account the skewness check of the distribution that we currently have in the code. 
Unless there's anything else to add, I can make a quick branch and a pull request with these changes.
