### ISSUE TITLE
Uncertainties in Vertex Positions

### ISSUE THREAD

**Issue by claudiopascoal** [NESTCollaboration/nest#131]
The uncertainties in the vertex positions should be modeled according to equation 4.2 in https://arxiv.org/pdf/1710.02752.pdf

σ_ver^2 = ((r_ver/r_S2)*σ_(x,y))^2 + σ_sys^2

σ_sys^2: This uncertainty does not depend on the number of photons that are emitted. It originates from the gate focusing effect, uncertainties in the drift of the electrons due to the variations in the field, etc. It was **3 mm** for LUX and we should use that same number for LZ (**3 mm** )

r_ver corresponds to the radius of the vertex position and r_S2 to the radius of the S2 light emission.

σ_(x,y) corresponds to the uncertainty in the position. It is modeled according to the equation 1 of that same article which is

σ_(x,y) = Y/sqrt(A_top)

Y: it is a constant - it was 7.5 in LUX for r<15 cm. Above 15 cm increased to about 11. 
For LZ - Y should be **11.6** which means that the uncertainties are larger for LZ compared with LUX. This is expected since the LZ PMTs are larger compared with LUX.

A_top: total area of the top array

**Comment by mszydagis** [comment]
Closing up since just got fixed in https://github.com/NESTCollaboration/nest/commit/acb88153733cd38f05b39d0af5888ae12ec07735
