### ISSUE TITLE
Unnecessary hardcoding of energy later in loopNEST

### ISSUE THREAD

**Issue by kmcmichael** [NESTCollaboration/nest#160]
See line 908 in execNEST.cpp
if ( loopNEST ) NRYieldsParam[4] = -TestSpectra::CH3T_spectrum(0.,18.6);
I believe this can just be removed.

**Comment by mszydagis** [comment]
hi Kirsten, this actually didn't work, please see https://github.com/NESTCollaboration/nest/commit/bfb279f3e218d1257ce2169487d05291db28d44f where I fixed this a different way than removing the line. It was necessary to keep for drawing new random energies for a continuous source like tritium. Also, note please I cannot reproduce your 1300 versus 1500 keV issue (I get 1490, which is close enough)
