### ISSUE TITLE
 NESTcalc::GetDriftVelocity_Liquid requires density as input, yet density is not used

### ISSUE THREAD

**Issue by YaniBion** [NESTCollaboration/nest#166]
In NEST.cpp line 2251, 
```
double NESTcalc::GetDriftVelocity_Liquid(
    double Kelvin, double eField,
    double Density) {  // for liquid and solid only

```
Yet density is not used?, it appears to be used only for GetDriftVelocity_MagBoltz, the gas density.

**Comment by mszydagis** [comment]
This is correct. It is there in case we need it in the future to more properly describe drift speed.

**Comment by YaniBion** [comment]
I'm not quite convinced. If that's the case, it should be commented explicitly in the function to make it more transparent.

**Comment by YaniBion** [comment]
Sorry I meant to close it.
