### ISSUE TITLE
G4Integrations problems as libNEST is not linked against G4 libraries

### ISSUE THREAD

**Issue by kreczko** [NESTCollaboration/nest#24]
When NEST is built with `G4=ON`, `libNEST.so` is not linked against the G4 libraries which causes errors:
```bash
Linking CXX executable ../bin/LZNESTUtilsTests
/cvmfs/lz.opensciencegrid.org/external/NEST/2.0.0/x86_64-slc6-gcc48-opt/lib/libNEST.so: undefined reference to `G4VProcess::DumpInfo() const'
/cvmfs/lz.opensciencegrid.org/external/NEST/2.0.0/x86_64-slc6-gcc48-opt/lib/libNEST.so: undefined reference to `G4VProcess::BuildWorkerPhysicsTable(G4ParticleDefinition const&)'
/cvmfs/lz.opensciencegrid.org/external/NEST/2.0.0/x86_64-slc6-gcc48-opt/lib/libNEST.so: undefined reference to `CLHEP::HepRandom::createInstance()'
/cvmfs/lz.opensciencegrid.org/external/NEST/2.0.0/x86_64-slc6-gcc48-opt/lib/libNEST.so: undefined reference to `typeinfo for G4UserStackingAction'
...
```

This can be remedied by linking anything linked against `libNEST.so` also against the G4 libraries, but that creates a lot of overhead. 

The following needs to be added to the `if(G4)` block
```cmake
target_link_libraries(NEST ${Geant4_LIBRARIES})
```

**Comment by jpbrodsky** [comment]
Good catch. I originally dealt with this by making non-G4 programs (like testNEST) link against libNESTcore instead of libNEST, but I never set up an install for NESTcore and I agree it's a bit of a fussy way to manage that. I like the new solution a lot better. Thanks!
