### ISSUE TITLE
bareNEST needs an update

### ISSUE THREAD

**Issue by xxiang4** [NESTCollaboration/nest#48]
When execute bareNEST, it says:
```
ERROR: You need a minimum of 12 nuisance parameters for the mean yields.
```
I think because bareNEST is still an example for the old NEST 2.0 version, which only requires 2 NuisParam.

**Comment by mszydagis** [comment]
Thank yo @xxiang4  this is corrected now in 6451ff159eca1062a6350a9df7d845291749ee80
