### ISSUE TITLE
Make the method WorkFunction static

### ISSUE THREAD

**Issue by riffard** [NESTCollaboration/nest#70]
Making the NESTCalc method `WorkFunction` static will be nice to allow user to use it without having to play with a `NESTCalc` object.

**Comment by mszydagis** [comment]
Acknowledged -- I will leave this issue open until it is done.

**Comment by mszydagis** [comment]
I am uploading fix soon @riffard today, but you should be aware in case it affects you, that it took extra changes, since the molar mass was needed to get accessed.
