### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by riffard** [NESTCollaboration/nest#73]
In the code, you are handling the error using the `exit` function. 
I would suggest to throw exception instead to allow a more flexible handling of the errors in codes calling NEST.
See this for reference: https://en.cppreference.com/w/cpp/error/exception

Here is an example to replace these lines https://github.com/NESTCollaboration/nest/blob/master/src/NEST.cpp#L1337: 
```c++
 if (gasGap <= 0. && E_liq > 0.) {
    throw std::runtime_error("ERR: The gas gap in the S2 calculation broke!!!!");
  }
```
As this is in the function `GetS2`, I would recommend to put a `try... catch` in `execNEST.cpp` such as: 
```C++
try{
    scint2= n.GetS2(quanta.electrons,truthPos[0],truthPos[1],truthPos[2],smearPos[0],smearPos[1],smearPos[2],
		        driftTime,vD,i,useField,0,verbosity,wf_time,wf_amp,g2_params);
}
catch(exception& e){

// Handle the exception here, you can then exit or use a return statement.

}
```

You will also need to include:
```C++
#include <exception>
```

**Comment by tunnell** [comment]
Just to warn you, this breaks compatibility with other libc versions.
