### ISSUE TITLE
Passing vector by reference

### ISSUE THREAD

**Issue by riffard** [NESTCollaboration/nest#91]
For the method [GetYieldNR](https://github.com/NESTCollaboration/nest/blob/master/include/NEST/NEST.hh#L208), it would be great to pass the `NuisParam ` vector by reference:

```
virtual YieldResult GetYieldNR(double energy, double density, double dfield, double massNum,
                  std::vector<double> &NuisParam={11.,1.1,0.0480,-0.0533,12.6,0.3,2.,0.3,2.,0.5,1.,1.});
```

**Comment by mszydagis** [comment]
We had this a few months ago, but then it stopped working -- I figured out why it was not working though, Quentin. Needs to be "const" as well. I've put it into the code, and will be pushing to master tonight, so I'm closing the issue
